### ISSUE TITLE
bytes

### ISSUE THREAD

**Issue by ApolloFN1w** [alxbrn/gdrv-loader#4]
with kdmapper i can load the driver from memory to then map a driver is that possible with this and if yes can you give me some pointers on how to do this? thanks in advance!

**Comment by westernA** [comment]
hey havocfn owner

**Comment by realnexlevel** [comment]
no, this disables DSE, loads ur driver normally just like any other driver and then reenables DSE. It is not a regular driver mapper, thats why this is called "loader", not mapper.
